# 修复服务端退出BUG

这个问题的关键所在是等待客户端连接的那个线程，在等待连接的时候阻塞了线程。

这个没办法用做标记的方法来处理，搜索了很长时间找到了解决办法。

`t.setDaemon(True)`:

主线程启动了子线程t，调用t.setDaemaon(True)，则主线程结束时，会把子线程t也杀死。

这样问题就完美的解决了。

修改后的代码见文件夹下的*server.py*。